# Generated by Django 5.2.16 on 2026-08-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('firm', 'Firm'), ('final', 'Final')], default='friendly', max_length=20)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
