# Generated by Django 5.2.17 on 2026-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email + WhatsApp')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('simulated', 'Simulated')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='wa_body',
            field=models.TextField(blank=True, default='', help_text='WhatsApp message body sent'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='wa_error',
            field=models.TextField(blank=True, help_text='Error details if WhatsApp send failed', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='wa_message_id',
            field=models.CharField(blank=True, help_text='Meta WhatsApp Cloud API message ID (wamid.*)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='wa_phone',
            field=models.CharField(blank=True, help_text='Recipient E.164 phone number used for WhatsApp send', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='wa_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('simulated', 'Simulated')], default='sent', help_text='Status of the WhatsApp send attempt', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('simulated', 'Simulated')], default='sent', max_length=20),
        ),
    ]
