# Generated by Django 5.2.17 on 2026-08-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brevo_api_key_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted Brevo API Key', null=True),
        ),
    ]
