# Generated by Django 5.2.17 on 2026-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_brevo_api_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='razorpay_key_id',
            field=models.CharField(blank=True, help_text='Razorpay Key ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='razorpay_key_secret_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted Razorpay Secret', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Default UPI ID for payment QR codes', max_length=255, null=True),
        ),
    ]
