# Generated by Django 5.2.17 on 2026-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wa_access_token_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted Permanent WhatsApp Cloud API Access Token', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wa_business_account_id',
            field=models.CharField(blank=True, help_text='Meta WhatsApp Business Account ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wa_phone_number_id',
            field=models.CharField(blank=True, help_text='Meta WhatsApp Phone Number ID (from Meta Developers Dashboard)', max_length=255, null=True),
        ),
    ]
